### ISSUE TITLE
Planejar e criar meta na carreira para 6 meses, 1 ano e 2 anos

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/my-study-plan#4]
- [ ] Planejar Meta na carreira para 6 meses
- [ ] Planejar Meta na carreira para 1 ano
- [ ] Planejar Meta na carreira para 2 anos
